use crate::domain::{CommitSummary, GitError, GitErrorCategory, GitResult, HistoryPage};

use std::collections::HashMap;

pub fn parse_log_with_stashes(
    data: &[u8],
    stash_map: &HashMap<String, String>,
) -> GitResult<Vec<CommitSummary>> {
    let commits = parse_log_records(data)?;
    Ok(filter_stash_plumbing_with_map(commits, stash_map))
}

pub fn parse_log(data: &[u8]) -> GitResult<Vec<CommitSummary>> {
    let commits = parse_log_records(data)?;
    Ok(filter_stash_plumbing_with_map(commits, &HashMap::new()))
}

fn parse_log_records(data: &[u8]) -> GitResult<Vec<CommitSummary>> {
    if data.is_empty() {
        return Ok(Vec::new());
    }
    let s = std::str::from_utf8(data).map_err(|e| GitError {
        category: GitErrorCategory::Parse,
        message: "Histórico inválido".into(),
        details: Some(e.to_string()),
    })?;
    let mut fields: Vec<_> = s.split('\0').collect();
    // `-z` adds one record terminator. Keep any preceding empty field: it is
    // the valid empty `%D` value for commits without refs.
    if fields.last() == Some(&"") {
        fields.pop();
    }
    if fields.len() % 6 != 0 {
        return Err(GitError {
            category: GitErrorCategory::Parse,
            message: "Histórico inválido".into(),
            details: Some("Registros de commit incompletos".into()),
        });
    }
    let mut commits = Vec::with_capacity(fields.len() / 6);
    for record in fields.as_chunks::<6>().0 {
        if record[0].is_empty() {
            return Err(GitError {
                category: GitErrorCategory::Parse,
                message: "Histórico inválido".into(),
                details: Some("Commit sem identificador".into()),
            });
        }
        let timestamp = record[3].parse().map_err(|_| GitError {
            category: GitErrorCategory::Parse,
            message: "Data de commit inválida".into(),
            details: None,
        })?;
        let refs = record[5]
            .split(", ")
            .filter(|x| !x.is_empty())
            .map(str::to_owned)
            .collect();
        commits.push(CommitSummary {
            oid: record[0].into(),
            parents: record[1].split_whitespace().map(str::to_owned).collect(),
            author: record[2].into(),
            timestamp,
            subject: record[4].into(),
            refs,
        });
    }
    Ok(commits)
}

pub fn filter_stash_plumbing(commits: Vec<CommitSummary>) -> Vec<CommitSummary> {
    filter_stash_plumbing_with_map(commits, &HashMap::new())
}

pub fn filter_stash_plumbing_with_map(
    mut commits: Vec<CommitSummary>,
    stash_map: &HashMap<String, String>,
) -> Vec<CommitSummary> {
    use std::collections::HashSet;
    let mut internal_stash_commits = HashSet::new();

    // 1. Identify stash commits and collect their internal plumbing parent OIDs
    for c in &commits {
        let is_stash = stash_map.contains_key(&c.oid)
            || c.refs.iter().any(|r| r.contains("stash"))
            || (c.parents.len() >= 2
                && (c.subject.starts_with("WIP on ") || c.subject.starts_with("On ")));

        if is_stash && c.parents.len() >= 2 {
            // c.parents[0] is the base HEAD commit
            // c.parents[1..] are the internal index / untracked plumbing commits
            for p in &c.parents[1..] {
                internal_stash_commits.insert(p.clone());
            }
        }
    }

    // 2. Also catch orphan untracked commits generated by git stash -u (which have 0 parents)
    for c in &commits {
        if c.parents.is_empty() && c.subject.starts_with("untracked files on ") {
            internal_stash_commits.insert(c.oid.clone());
        }
    }

    if !internal_stash_commits.is_empty() {
        // 3. Remove internal plumbing commits
        commits.retain(|c| !internal_stash_commits.contains(&c.oid));
    }

    // 4. Prune stash parents to only retain parent 0 (the base commit) and assign exact stash ref
    for c in &mut commits {
        if let Some(stash_ref) = stash_map.get(&c.oid) {
            c.parents.retain(|p| !internal_stash_commits.contains(p));
            c.refs.retain(|r| r != "refs/stash" && r != "stash");
            if !c.refs.contains(stash_ref) {
                c.refs.push(stash_ref.clone());
            }
        } else {
            let is_stash = c.refs.iter().any(|r| r.contains("stash"))
                || (c.parents.len() >= 2
                    && (c.subject.starts_with("WIP on ") || c.subject.starts_with("On ")));

            if is_stash {
                c.parents.retain(|p| !internal_stash_commits.contains(p));
                // Ensure stash ref tag exists if missing from log formatting
                if c.refs.is_empty() {
                    c.refs.push("refs/stash".into());
                }
            }
        }
    }

    commits
}

pub fn page(commits: Vec<CommitSummary>, limit: usize) -> HistoryPage {
    let has_more = commits.len() > limit;
    HistoryPage {
        commits: commits.into_iter().take(limit).collect(),
        has_more,
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn filters_stash_internal_commits_and_preserves_clean_base_parent() {
        let base = CommitSummary {
            oid: "base1".into(),
            parents: vec![],
            refs: vec!["main".into()],
            author: "User".into(),
            timestamp: 100,
            subject: "Initial commit".into(),
        };
        let untracked = CommitSummary {
            oid: "u1".into(),
            parents: vec![],
            refs: vec![],
            author: "User".into(),
            timestamp: 200,
            subject: "untracked files on main: base1 Initial commit".into(),
        };
        let index = CommitSummary {
            oid: "i1".into(),
            parents: vec!["base1".into()],
            refs: vec![],
            author: "User".into(),
            timestamp: 200,
            subject: "index on main: base1 Initial commit".into(),
        };
        let stash = CommitSummary {
            oid: "s1".into(),
            parents: vec!["base1".into(), "i1".into(), "u1".into()],
            refs: vec!["refs/stash".into()],
            author: "User".into(),
            timestamp: 200,
            subject: "WIP on main: base1 Initial commit".into(),
        };

        let commits = vec![stash, index, untracked, base];
        let filtered = filter_stash_plumbing(commits);

        assert_eq!(filtered.len(), 2);
        assert_eq!(filtered[0].oid, "s1");
        assert_eq!(filtered[0].parents, vec!["base1"]);
        assert_eq!(filtered[1].oid, "base1");
    }
}
