import { expect, test } from '@playwright/test'

test.describe('fluxos do workspace', () => {
  test('local: seleciona arquivo, preserva mensagem ao atualizar e alterna stage', async ({ page }) => {
    await page.goto('/?fixture=local')
    await expect(page.getByRole('heading', { name: 'Alterações locais' })).toBeVisible()
    const file = page.getByRole('button', { name: /schema\.prisma/i })
    await file.click()
    await expect(page.locator('.monaco-host')).toBeVisible()
    await page.locator('#commit-message').fill('Preservar estado durante atualização')
    await page.getByTitle(/Atualizar/).click()
    await expect(page.locator('#commit-message')).toHaveValue('Preservar estado durante atualização')
    await expect(file).toHaveAttribute('aria-current', 'true')
    await page.evaluate(() => document.querySelector('.monaco-host')?.setAttribute('data-editor-identity', 'preserve'))
    await page.getByTitle(/Atualizar/).click()
    await expect(page.locator('.monaco-host')).toHaveAttribute('data-editor-identity', 'preserve')
    await expect(page.locator('.monaco-editor .view-lines').first()).toContainText('refreshRepository')
    const checkbox = page.getByRole('checkbox', { name: /schema\.prisma/i })
    await checkbox.check()
    await expect(page.getByText('Em stage').locator('..').getByText('3', { exact: true })).toBeVisible()
    await page.getByRole('button', { name: /Criar commit/i }).click()
    await expect(page.locator('#commit-message')).toHaveValue('')
    await page.screenshot({ path: 'target/visual/workflow-local.png', fullPage: true })
  })

  test('histórico alterna os dois modos com conteúdo real e não exibe stage', async ({ page }) => {
    await page.goto('/?fixture=history')
    await expect(page.getByRole('heading', { name: 'Histórico' })).toBeVisible()
    const commitRow = page.locator('button.lists-graph-row').filter({ hasText: 'Refine repository workspace' })
    await expect(commitRow).toBeVisible()
    await commitRow.click()
    await expect(page.getByRole('heading', { name: 'Arquivos do commit' })).toBeVisible()
    await page.getByRole('button', { name: /app\.ts/i }).click()
    await expect(page.locator('.monaco-host')).toBeVisible()
    await expect(page.locator('.monaco-editor .view-lines').first()).toContainText('refreshRepository')
    await page.getByTitle('Lado a lado').click()
    await expect(page.locator('.monaco-editor.original-in-monaco-diff-editor')).toBeVisible()
    await page.getByTitle('Unificado').click()
    await expect(page.locator('.monaco-editor .view-lines').first()).toContainText('refreshRepository')
    await expect(page.getByRole('checkbox')).toHaveCount(0)
    await expect(page.getByRole('button', { name: /Criar commit/i })).toHaveCount(0)
    await page.setViewportSize({ width: 1100, height: 700 })
    await expect.poll(() => page.evaluate(() => document.documentElement.scrollWidth <= document.documentElement.clientWidth)).toBe(true)
    await page.screenshot({ path: 'target/visual/workflow-history.png', fullPage: true })
  })

  test('conflito bloqueia commit e fixture binary informa indisponibilidade', async ({ page }) => {
    await page.goto('/?fixture=conflict')
    await expect(page.getByRole('button', { name: /Criar commit/i })).toBeDisabled()
    await page.goto('/?fixture=binary')
    await expect(page.getByText('Arquivo binário', { exact: true })).toBeVisible()
  })
})
